[
            {
               "name": "_Tizian",
                "uuid": "5b48ca54-49c7-495f-815a-29c561f1e319",
                "enabled": "true",
                "cape-style": "",
		"cape-enabled": "false",
                "hat-enabled": "false",
                "hat-r": "12",
		"hat-g": "255",
		"hat-b": "90",
            	"wings-enabled": "true",
             	"wings-r": "0.1F",
		"wings-g": "0.1F",
		"wings-b": "0.1F",
		"eastereggs-enabled": "false",
		"ghast-enabled": "false",
                "ghostwings-enabled": "false",
                "ghostwings-r": "12",
		"ghostwings-g": "255",
		"ghostwings-b": "90",
		"kreuze-enabled": "false",
                "kreuze-r": "12",
		"kreuze-g": "255",
		"kreuze-b": "90",
		"heart-enabled": "false",
		"susanoo-enabled": "true",
                "susanoo-r": "0.1",
		"susanoo-g": "0.1",
		"susanoo-b": "0.1",
		"villigernose-enabled": "false",
                "villigernose-r": "12",
		"villigernose-g": "255",
		"villigernose-b": "90",
		"villigerhead-enabled": "false",
		"brille-enabled": "false",
                "brille-r": "12",
		"brille-g": "255",
		"brille-b": "90",
		"censored-enabled": "false",
		"mask-enabled": "false",
		"glasses-enabled": "false",
		"ender-particle-enabled": "false",
		"entchant-particle-enabled": "false",
		"town-particle-enabled": "true"
		    
            }
	
	
	]
